# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170621_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_data',
            new_name='publication_date',
        ),
    ]
